# General Settings
now_dir: ${now:%Y-%m-%d}/${now:%H-%M-%S}
mixed_precision: fp16  # choices: ["no", "fp16", "bf16"]
output_dir: outputs/${now_dir}
seed: 42
pretrained_model_path: models/basemodel
finetuned_model_path: outputs/2025-03-17/00-42-22/checkpoint-30000
enable_xformers_memory_efficient_attention: false

reference_dir: data/celeba_test_single
max_num_objects: 10
num_images_per_prompt: 1
inference_steps: 50
generate_height: 512
generate_width: 512
guidance_scale: 5
start_merge_step: 10

# Model Settings
revision: null
non_ema_revision: null
object_localization: false
object_localization_weight: 0.0
localization_layers: 0
mask_loss: 0.0
mask_loss_prob: 0.0
object_localization_threshold: 0.0
object_localization_normalize: 0.0
image_encoder_name_or_path: openai/clip-vit-large-patch14
no_object_augmentation: true
object_resolution: 224
image_encoder_type: clip


caption_list:
  - a man <|image|> reading book
  - a man <|image|> wearing a red hat
  - a man <|image|> wearing a santa hat
  - a man <|image|> wearing a rainbow scarf
  - a man <|image|> wearing a black top hat and a monocle
  - a man <|image|> in a chef outfit
  - a man <|image|> in a firefighter outfit
  - a man <|image|> in a police outfit
  - a man <|image|> wearing pink glasses
  - a man <|image|> wearing a yellow shirt
  - a man <|image|> in a purple wizard outfit
  - a man <|image|> is in the jungle
  - a man <|image|> is in the snow
  - a man <|image|> is on the beach
  - a man <|image|> is on a cobblestone street
  - a man <|image|> is on top of pink fabric
  - a man <|image|> is on top of a wooden floor
  - a man <|image|> is with a city in the background
  - a man <|image|> is with a mountain in the background
  - a man <|image|> is with a blue house in the background
  - a man <|image|> is on top of a purple rug in a forest
  - a man <|image|> is riding a horse
  - a man <|image|> is holding a glass of wine
  - a man <|image|> is holding a piece of cake
  - a man <|image|> is giving a lecture
  - a man <|image|> is gardening in the backyard
  - a man <|image|> is cooking a meal
  - a man <|image|> is working out at the gym
  - a man <|image|> is walking the dog
  - a man <|image|> is baking cookies

# Custom
face_separation: False
face_expression: False
face_separation_weight: 
face_separation_delta: 
