# General Settings
now_dir: ${now:%Y-%m-%d}/${now:%H-%M-%S}
mixed_precision: fp16  # choices: ["no", "fp16", "bf16"]
output_dir: outputs/${now_dir}
seed: 42
pretrained_model_path: models/basemodel
finetuned_model_path: outputs/2024-11-26/13-16-21/checkpoint-3400
enable_xformers_memory_efficient_attention: false

# v1 face: outputs/2024-10-29/19-10-11/checkpoint-3200
# v2 expression: outputs/2024-11-26/13-16-21/checkpoint-3400

reference_dir: data/celeba_test_single
max_num_objects: 10
num_images_per_prompt: 1
inference_steps: 50
generate_height: 512
generate_width: 512
guidance_scale: 5
start_merge_step: 10

# Model Settings
revision: null
non_ema_revision: null
object_localization: false
object_localization_weight: 0.0
localization_layers: 0
mask_loss: 0.0
mask_loss_prob: 0.0
object_localization_threshold: 0.0
object_localization_normalize: 0.0
image_encoder_name_or_path: openai/clip-vit-large-patch14
no_object_augmentation: true
object_resolution: 224
image_encoder_type: clip


caption_list:
  - a man <|image|> reading book
  - a man <|image|> wearing a red hat
  - a man <|image|> wearing a santa hat
  - a man <|image|> wearing a rainbow scarf
  - a man <|image|> wearing a black top hat and a monocle
  - a man <|image|> in a chef outfit
  - a man <|image|> in a firefighter outfit
  - a man <|image|> in a police outfit
  - a man <|image|> wearing pink glasses
  - a man <|image|> wearing a yellow shirt
  - a man <|image|> in a purple wizard outfit
  - a man <|image|> is in the jungle
  - a man <|image|> is in the snow
  - a man <|image|> is on the beach
  - a man <|image|> is on a cobblestone street
  - a man <|image|> is on top of pink fabric
  - a man <|image|> is on top of a wooden floor
  - a man <|image|> is with a city in the background
  - a man <|image|> is with a mountain in the background
  - a man <|image|> is with a blue house in the background
  - a man <|image|> is on top of a purple rug in a forest
  - a man <|image|> is riding a horse
  - a man <|image|> is holding a glass of wine
  - a man <|image|> is holding a piece of cake
  - a man <|image|> is giving a lecture
  - a man <|image|> is gardening in the backyard
  - a man <|image|> is cooking a meal
  - a man <|image|> is working out at the gym
  - a man <|image|> is walking the dog
  - a man <|image|> is baking cookies
  # added prompt
  - A confident pilot <|image|>, with aviator sunglasses, a leather bomber jacket, and a scarf billowing in the wind, standing in front of an old-fashioned biplane, his face half-lit by the setting sun.
  - A thoughtful artist <|image|>, brush in hand, deep in concentration, wearing a paint-splattered apron, standing in front of a massive canvas, colors swirling in abstract patterns, sunlight filtering through the studio window onto his serene expression.
  - A stern soldier <|image|>, with a neatly trimmed beard, wearing a dusty camouflage uniform and a beret, standing at attention in front of a military tent, his intense gaze focused on the horizon.
  - A jubilant football coach <|image|>, whistle hanging from his neck, arms raised in victory, wearing a team jacket and cap, standing on the sidelines of a stadium, the roaring crowd behind him blurring in the background.
  - A weary traveler <|image|>, with a rugged beard, backpack slung over his shoulder, a wide-brimmed hat shading his tired eyes, standing on a mountain trail as twilight descends, distant peaks silhouetted against the sky.
  - A relaxed beachgoer <|image|>, reclining on a sun lounger, sunglasses on his face, wearing a floral-patterned shirt and holding a coconut drink with an umbrella, the ocean waves gently crashing behind him, a satisfied smile on his face.
  - A charismatic magician <|image|>, in a black tuxedo with a red rose on the lapel, performing a card trick, his gloved hands moving swiftly, a top hat sitting on his head, eyes gleaming with mischief, the stage lights reflecting in his gaze.
  - A contemplative philosopher <|image|>, sitting at a rustic wooden desk, quill in hand, surrounded by ancient books and scrolls, candlelight flickering on his face as he gazes out of a small window, pondering the mysteries of the universe.
  - A cheerful bartender <|image|>, with a slicked-back hairstyle, wearing a white shirt and black vest, shaking a cocktail mixer, standing behind a polished wooden bar, bottles of liquor lined up neatly in the background, a playful grin on his face.
  - A daring astronaut <|image|>, visor up, revealing a determined expression, wearing a white spacesuit, floating just outside a space station, Earth looming large in the background, the Milky Way stretching out behind him in the endless void.
  - A focused chef <|image|>, with a white apron tied around his waist, meticulously plating a gourmet dish, the kitchen bustling behind him, steam rising from pots, his face set in concentration, but his eyes gleaming with passion for his craft.
  - A mysterious spy <|image|>, in a sleek black suit, adjusting his cufflinks, standing in the shadows of a dimly lit parking garage, his face partially obscured by darkness, but his piercing eyes visible, a sleek black car waiting behind him.
  - A proud sailor <|image|>, standing at the bow of a ship, hands gripping the railing, his captain's hat firmly on his head, looking out to sea, the salty breeze blowing through his hair, waves crashing against the hull, determination in his eyes.
  - A joyful musician <|image|>, playing a saxophone on a dimly lit stage, eyes closed in deep concentration, wearing a loose-fitting suit and a fedora, the spotlight catching the sweat on his brow, the sound of jazz filling the smoky room.
  - A reflective scholar <|image|>, wearing round glasses, his fingers tracing the spine of an ancient tome in a grand library, sunlight streaming through stained-glass windows onto rows of leather-bound books, a peaceful smile on his face as he contemplates his next discovery.

# Custom
face_separation: False
face_expression: False
face_separation_weight: 
face_separation_delta: 


# Inference
# caption_list: