# General Settings
now_dir: ${now:%Y-%m-%d}/${now:%H-%M-%S}
output_dir: outputs/${now_dir}


# input
reference_image: data/celeba/000023/000023_hb_x4_resize.png
generated_image: outputs/2024-09-13/23-50-24/output_0.png
generated_image_dir: data/uniportrait

# for vlm 
few_shot_example: data/example/merged_image.png
request_for_image: 1
model: gemini-1.5-pro-latest # gpt-4o, gemini-1.5-flash-latest, gemini-1.5-pro-latest